### ISSUE TITLE
Иммутабельность данных

### ISSUE THREAD

**Issue by Azmodan95** [Aleinbanger/toxin-website#1]
Нужно стараться делать данные не изменяемыми.
К примеру здесь происходит мутирование pug объекта attributes, чтобы этого избежать можно ведь создать новый объект, к примеру 
```
const params = {
      type: 'button',
      title: 'likeCount',
      'data-active': active,
      class: [blockName, `js-${blockName}`, active && `${blockName}_active`],
}
```
И затем уже передавать этот объект `button&attributes(params)`. 

---

https://github.com/Aleinbanger/toxin-website/blob/4e6d78894771973ae87dc330a6601e4204b5f535/source/blocks/button-like/button-like.pug#L9
Здесь так же можно обойдись без изменения значения переменной в процессе, достаточно использовать тернарный оператор `const icon = active ? 'favorite' : 'favorite_border';`

---

https://github.com/Aleinbanger/toxin-website/blob/4e6d78894771973ae87dc330a6601e4204b5f535/source/blocks/button/button.pug#L12
В подобных случаях, чтобы избежать изменения значения переменной, достаточно использовать объект:
```
const btnTag = {
      'link': 'a';
      'button': 'button'
};
#{btnTag[buttonType]}&attributes(attributes) #{btnText}
```
Но это если много вариаций будет, в данном случае так как вариации всего две, вполне можно обойтись тернарным оператором `const btnTag = btnType === 'link' ? 'a' : 'button';`

**Comment by Aleinbanger** [comment]
Прошёлся по всем блокам, исправил следующим образом:
https://github.com/Aleinbanger/toxin-website/blob/f644c5d0f9d91b3f5af1394a2e991d18c6171424/source/blocks/button-like/button-like.pug#L14
Объект `attributes` всё равно нужен, потому что я использую его для передачи html атрибутов в миксины, чтобы не плодить лишние аргументы. Как здесь например:
https://github.com/Aleinbanger/toxin-website/blob/f644c5d0f9d91b3f5af1394a2e991d18c6171424/source/blocks/card-signup/card-signup.pug#L18
