### ISSUE TITLE
Сокращения 

### ISSUE THREAD

**Issue by Olga-Skoroded** [Aleinbanger/toxin-website#7]
Использовать сокращения в именовании не очень хорошо, т.к. это ухудшает читаемость и поиск по проекту

**Comment by Aleinbanger** [comment]
А о каких сокращениях речь, например? Вот сейчас нашёл только `min`, `max`, `btn`, `tmp`, `img`, `src`, `fst`, `snd`. Где-то в best practice читал, что общепринятые сокращения, такие как btn, допустимы. Например, имя переменной `imgSrcList` плохо? переименовать в `imageSourceList`? Что насчёт `min`, `max`?
