### ISSUE TITLE
Префикс js

### ISSUE THREAD

**Issue by Olga-Skoroded** [Aleinbanger/toxin-website#8]
Вот тут почему то отличается именование класса с префиксом
.search-room__filter-item должно быть .js-search-room__filter-item, а у тебя .js-search-room__dropdown-date
Проверь пожалуйста, чтобы по всему проекту класс с префиксом соответствовал классу без префикса 
![Снимок экрана от 2021-08-17 17-22-17](https://user-images.githubusercontent.com/68814270/129724910-20e0ae79-5cc2-4ce1-91e7-c10efba15c73.png)

**Comment by Aleinbanger** [comment]
Хм, но ведь `.search-room__filter-item` - это контейнер, который повторяется и может содержать что угодно. А `.js-search-room__dropdown-date` - конкретная роль для dropdown-date.
Может, тогда сделать такой класс `.search-room__filter-item.search-room__filter-item_closest.search-room__dropdown-date.js-search-room__dropdown-date`?
Но тогда класс `.search-room__dropdown-date` будет пустой.
